### ISSUE TITLE
Up to date packages.txt

### ISSUE THREAD

**Issue by dovry** [dovry/debloat-samsung-galaxy#2]
https://hackerztrickz.com/list-of-samsung-bloatware-safe-to-remove/#List_of_Samsung_Bloatware_Safe_to_Remove

https://www.minitool.com/news/list-of-samsung-bloatware-safe-to-remove.html

**Comment by dandv** [comment]
How about joining forces with @khlam's [debloat-samsung-android](https://github.com/khlam/debloat-samsung-android) and [adding descriptions](https://github.com/khlam/debloat-samsung-android/issues/39)?

**Comment by dovry** [comment]
I don't have an android anymore, so I'm not interested in maintaining this repo until I do.
